// @vitest-environment jsdom
import{act,cleanup,fireEvent,render,screen}from"@testing-library/react";import{afterEach,describe,expect,it,vi}from"vitest";
import KidlinRuleExperiment from"../experiments/KidlinRuleExperiment";import PremackPrincipleExperiment from"../experiments/PremackPrincipleExperiment";import TenMinuteWallStareExperiment,{WALL_STARE_SECONDS}from"../experiments/TenMinuteWallStareExperiment";import StrooperEffectExperiment from"../experiments/StrooperEffectExperiment";import TwoXVideoSpeedExperiment from"../experiments/TwoXVideoSpeedExperiment";
import{kidlinRuleExperiment,premackPrincipleExperiment,wallStareExperiment,strooperEffectExperiment,twoXVideoExperiment}from"../methodLabData";import{kidlinRuleMatchData,premackPrincipleMatchData,wallStareMatchData,strooperEffectMatchData,twoXVideoMatchData}from"../methodMatchData";
afterEach(()=>{cleanup();vi.useRealTimers()});
function advanceKidlin(){fireEvent.click(screen.getByRole("button",{name:"Start clarification"}));for(const [placeholder,label]of [["Describe the observable situation...","Remove ambiguity"],["Rewrite ambiguous or general wording...","Identify the obstacle"],["Identify the real obstacle...","Rewrite the problem"],["Write one precise actionable statement...","Continue"]]){fireEvent.change(screen.getByPlaceholderText(placeholder),{target:{value:"A specific response with enough detail."}});fireEvent.click(screen.getByRole("button",{name:label}))}}
describe("focus and clarification method workflows",()=>{
 it("supports both Kidlin optional-analysis paths without changing the objective test",()=>{render(<KidlinRuleExperiment method="kidlin-rule" category="problem-solving" name="Kidlin's rule" data={kidlinRuleExperiment} onComplete={vi.fn()}/>);advanceKidlin();fireEvent.click(screen.getByRole("button",{name:"Skip and continue"}));expect(screen.getByText("APPLICATION TEST")).toBeTruthy();cleanup();render(<KidlinRuleExperiment method="kidlin-rule" category="problem-solving" name="Kidlin's rule" data={kidlinRuleExperiment} onComplete={vi.fn()}/>);advanceKidlin();fireEvent.click(screen.getByRole("button",{name:"Analyze deeper"}));for(const [placeholder,label]of [["Define boundaries, parameters, and the exact situation...","Continue"],["Separate observable behaviors from contextual factors...","Compare patterns"],["Compare repeated behavior and context patterns...","Analyze relationships"],["Cross-reference patterns and identify the most plausible root cause...","Continue to test"]]){fireEvent.change(screen.getByPlaceholderText(placeholder),{target:{value:"A detailed optional analysis response."}});fireEvent.click(screen.getByRole("button",{name:label}))}expect(screen.getByText("APPLICATION TEST")).toBeTruthy()});
 it("pairs a less-preferred task with a later preferred activity",()=>{render(<PremackPrincipleExperiment method="premack-principle" category="focus" name="Premack's principle" data={premackPrincipleExperiment} onComplete={vi.fn()}/>);fireEvent.click(screen.getByRole("button",{name:"Start experiment"}));fireEvent.change(screen.getByPlaceholderText("Name the less-preferred learning task..."),{target:{value:"Review vocabulary"}});fireEvent.change(screen.getByPlaceholderText("Name the preferred activity afterward..."),{target:{value:"Play a game"}});fireEvent.click(screen.getByRole("button",{name:"Commit to task first"}));expect(screen.getByText(premackPrincipleExperiment.material)).toBeTruthy()});
 it("keeps the wall reset locked for the full 600 seconds",()=>{vi.useFakeTimers();render(<TenMinuteWallStareExperiment method="ten-minute-wall-stare" category="focus" name="10 min wall stare" data={wallStareExperiment} onComplete={vi.fn()}/>);fireEvent.click(screen.getByRole("button",{name:"Begin 10-minute reset"}));const button=screen.getByRole("button",{name:"Start studying"})as HTMLButtonElement;expect(button.disabled).toBe(true);act(()=>vi.advanceTimersByTime((WALL_STARE_SECONDS-1)*1000));expect(button.disabled).toBe(true);act(()=>vi.advanceTimersByTime(1000));expect((screen.getByRole("button",{name:"Start studying"})as HTMLButtonElement).disabled).toBe(false)});
 it("reuses the Strooper interaction and requires eight attempts",()=>{render(<StrooperEffectExperiment method="strooper-effect" category="focus" name="Strooper effect" data={strooperEffectExperiment} onComplete={vi.fn()}/>);fireEvent.click(screen.getByRole("button",{name:"Start attention task"}));const next=screen.getByRole("button",{name:"Continue to learning"})as HTMLButtonElement;expect(next.disabled).toBe(true);for(let i=0;i<8;i+=1)fireEvent.click(document.querySelector("#PROMPT")as HTMLElement);expect(next.disabled).toBe(false)});
 it("sets local instructional media to 2x playback",()=>{render(<TwoXVideoSpeedExperiment method="two-x-video-speed" category="understanding" name="2X video speed" data={twoXVideoExperiment} onComplete={vi.fn()}/>);fireEvent.click(screen.getByRole("button",{name:"Start 2x playback"}));expect((document.querySelector("video")as HTMLVideoElement).playbackRate).toBe(2)});
 it("uses unseen topics and stimuli for every method",()=>{expect(kidlinRuleMatchData.topic).not.toBe(kidlinRuleExperiment.topic);expect(premackPrincipleMatchData.topic).not.toBe(premackPrincipleExperiment.topic);expect(wallStareMatchData.topic).not.toBe(wallStareExperiment.topic);expect(strooperEffectMatchData.topic).not.toBe(strooperEffectExperiment.topic);expect(strooperEffectMatchData.colors).not.toEqual(strooperEffectExperiment.colors);expect(twoXVideoMatchData.topic).not.toBe(twoXVideoExperiment.topic);expect(twoXVideoMatchData.mediaSrc).not.toBe(twoXVideoExperiment.mediaSrc)});
});
